/**
 * Demo Data for HomeScout
 *
 * This file contains sample data for demonstrating the app's features
 * to both home buyers and real estate professionals.
 */

import { User, Property, Client, Showing, Household, FinancialProfile, HomeBuyerProfile, BrokerProfile } from '../types';

// Demo User IDs
export const DEMO_BUYER_ID = 'demo-buyer-001';
export const DEMO_BROKER_ID = 'demo-broker-001';
export const DEMO_HOUSEHOLD_ID = 'demo-household-001';

// Demo Household
export const demoHousehold: Household = {
  id: DEMO_HOUSEHOLD_ID,
  name: 'Demo Household',
  invite_code: 'DEMO123',
  created_at: new Date().toISOString(),
  settings: {
    commute_destinations: [
      { name: 'Downtown Office', address: '100 Main St, San Francisco, CA 94102' },
      { name: 'Tech Campus', address: '1 Hacker Way, Menlo Park, CA 94025' },
    ],
    default_interest_rate: 6.5,
    default_down_payment_percent: 20,
    default_loan_term_years: 30,
    target_dti: 36,
  },
};

// Demo Buyer Profile
export const demoBuyerProfile: HomeBuyerProfile = {
  phone: '(555) 123-4567',
  preferred_contact: 'email',
  budget_min: 650000,
  budget_max: 950000,
  min_beds: 3,
  min_baths: 2,
  min_sqft: 1800,
  max_sqft: 3000,
  preferred_cities: ['San Francisco', 'Oakland', 'Berkeley'],
  timeline: '1-3_months',
  pre_approved: true,
  pre_approval_amount: 900000,
  areas_of_interest: ['South Bay', 'East Bay', 'Peninsula'],
  property_types: ['Single Family', 'Townhouse'],
  must_haves: ['Garage', 'Backyard', 'Updated Kitchen', 'Good Schools'],
  deal_breakers: ['Busy Street', 'No Parking', 'Major Repairs Needed'],
};

// Demo Financial Profile
export const demoFinancialProfile: FinancialProfile = {
  annual_household_income: 280000,
  additional_annual_income: 15000,
  monthly_debt_payments: 800,
  available_down_payment: 180000,
  total_savings: 250000,
  credit_score_range: 'excellent',
  target_monthly_payment: 5500,
  max_dti_percent: 36,
  investment_horizon_years: 7,
  rental_income_potential: true,
  first_time_buyer: false,
};

// Demo Broker Profile
export const demoBrokerProfile: BrokerProfile = {
  phone: '(555) 987-6543',
  company_name: 'Premier Realty Group',
  license_number: 'DRE01234567',
  license_state: 'CA',
  years_experience: 12,
  specializations: ['Luxury Homes', 'First-Time Buyers', 'Investment Properties', 'Relocation'],
  service_areas: ['San Francisco', 'Marin County', 'East Bay', 'Peninsula'],
  bio: 'Top-producing agent with over $50M in annual sales. Specializing in helping families find their dream homes.',
  website: 'www.premierrealty.demo',
};

// Demo Buyer User
export const demoBuyerUser: User = {
  id: DEMO_BUYER_ID,
  household_id: DEMO_HOUSEHOLD_ID,
  email: 'demo.buyer@homescout.app',
  name: 'Alex & Jordan Demo',
  avatar_url: undefined,
  user_type: 'individual',
  preferences: {
    notifications_enabled: true,
    profile: demoBuyerProfile,
  },
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
};

// Demo Broker User
export const demoBrokerUser: User = {
  id: DEMO_BROKER_ID,
  household_id: DEMO_HOUSEHOLD_ID,
  email: 'demo.broker@homescout.app',
  name: 'Sarah Mitchell',
  avatar_url: undefined,
  user_type: 'broker',
  company_name: 'Premier Realty Group',
  preferences: {
    notifications_enabled: true,
    profile: demoBrokerProfile,
  },
  created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(), // 1 year ago
};

// Helper to generate days ago date
const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

// Demo Properties - Diverse mix for showcasing features
export const demoProperties: Property[] = [
  {
    id: 'demo-prop-001',
    household_id: DEMO_HOUSEHOLD_ID,
    address: '742 Maple Street',
    city: 'San Francisco',
    state: 'CA',
    zip: '94110',
    county: 'San Francisco',
    price: 875000,
    beds: 3,
    baths: 2,
    full_baths: 2,
    half_baths: 0,
    sqft: 1850,
    lot_size: 2500,
    year_built: 1925,
    year_renovated: 2019,
    garage: 1,
    stories: 2,
    rooms: 7,
    hoa_monthly: 0,
    property_tax_annual: 10500,
    insurance_annual: 1800,
    status: 'toured',
    mls_number: 'SF12345678',
    listing_date: daysAgo(12),
    property_type: 'Single Family',
    property_style: 'Victorian',
    interior_features: ['Hardwood Floors', 'Crown Molding', 'Built-in Shelves', 'Bay Windows', 'Fireplace'],
    exterior_features: ['Deck', 'Fenced Yard', 'Garden', 'Outdoor Lighting'],
    appliances: ['Stainless Steel Refrigerator', 'Gas Range', 'Dishwasher', 'Washer/Dryer'],
    flooring: ['Hardwood', 'Tile'],
    heating: 'Forced Air',
    cooling: 'None',
    basement: 'Full - Finished',
    garage_type: ['Attached'],
    roof: 'Composition',
    sewer: 'Public',
    water: 'Public',
    has_in_law_suite: false,
    remarks: 'Stunning Victorian home in the heart of Noe Valley. Recently renovated with modern amenities while preserving original character. Sun-filled living spaces, chef\'s kitchen with quartz countertops, and a peaceful backyard perfect for entertaining. Walking distance to 24th Street shops and restaurants.',
    original_list_price: 899000,
    price_per_sqft: 473,
    days_on_market: 12,
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(10),
    updated_at: daysAgo(2),
    photos: [
      { id: 'photo-001', property_id: 'demo-prop-001', url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800', caption: 'Front Exterior', is_primary: true, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(10) },
      { id: 'photo-002', property_id: 'demo-prop-001', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', caption: 'Living Room', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(10) },
      { id: 'photo-003', property_id: 'demo-prop-001', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800', caption: 'Kitchen', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(10) },
    ],
    ratings: [
      { id: 'rating-001', property_id: 'demo-prop-001', user_id: DEMO_BUYER_ID, rating: 4, created_at: daysAgo(5), updated_at: daysAgo(5) },
    ],
    notes: [
      { id: 'note-001', property_id: 'demo-prop-001', user_id: DEMO_BUYER_ID, content: 'Love the original hardwood floors and bay windows!', type: 'pro', created_at: daysAgo(5) },
      { id: 'note-002', property_id: 'demo-prop-001', user_id: DEMO_BUYER_ID, content: 'Kitchen was recently updated with high-end appliances', type: 'pro', created_at: daysAgo(5) },
      { id: 'note-003', property_id: 'demo-prop-001', user_id: DEMO_BUYER_ID, content: 'Street can be noisy during rush hour', type: 'con', created_at: daysAgo(5) },
    ],
    tags: [
      { id: 'tag-001', property_id: 'demo-prop-001', tag: 'Victorian', created_at: daysAgo(10) },
      { id: 'tag-002', property_id: 'demo-prop-001', tag: 'Renovated', created_at: daysAgo(10) },
      { id: 'tag-003', property_id: 'demo-prop-001', tag: 'Backyard', created_at: daysAgo(10) },
    ],
  },
  {
    id: 'demo-prop-002',
    household_id: DEMO_HOUSEHOLD_ID,
    address: '1580 Pacific Heights Blvd',
    city: 'San Francisco',
    state: 'CA',
    zip: '94115',
    county: 'San Francisco',
    price: 1250000,
    beds: 4,
    baths: 3,
    full_baths: 2,
    half_baths: 1,
    sqft: 2400,
    lot_size: 3200,
    year_built: 1910,
    year_renovated: 2021,
    garage: 2,
    stories: 3,
    rooms: 9,
    hoa_monthly: 0,
    property_tax_annual: 15000,
    insurance_annual: 2400,
    status: 'interested',
    mls_number: 'SF23456789',
    listing_date: daysAgo(3),
    property_type: 'Single Family',
    property_style: 'Edwardian',
    interior_features: ['Gourmet Kitchen', 'Home Office', 'Wine Cellar', 'Smart Home System', 'Dual Pane Windows'],
    exterior_features: ['Rooftop Deck', 'Hot Tub', 'Landscaped Garden', '2-Car Garage'],
    appliances: ['Sub-Zero Refrigerator', 'Wolf Range', 'Wine Cooler', 'Built-in Espresso Machine'],
    flooring: ['Hardwood', 'Marble', 'Heated Floors'],
    heating: 'Radiant',
    cooling: 'Central AC',
    basement: 'Full - Wine Cellar',
    garage_type: ['Attached', 'Electric Vehicle Charging'],
    roof: 'Slate',
    sewer: 'Public',
    water: 'Public',
    has_in_law_suite: true,
    in_law_features: ['Separate Entrance', 'Kitchenette', 'Full Bath'],
    remarks: 'Exquisite Pacific Heights masterpiece with breathtaking Bay views. This meticulously renovated Edwardian features 4 bedrooms, including a stunning primary suite with spa bath. Gourmet kitchen with professional appliances, home office, and a legal in-law unit. Rooftop deck offers panoramic views of the Golden Gate Bridge.',
    original_list_price: 1295000,
    price_per_sqft: 521,
    days_on_market: 3,
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
    photos: [
      { id: 'photo-004', property_id: 'demo-prop-002', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', caption: 'Front View', is_primary: true, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(3) },
      { id: 'photo-005', property_id: 'demo-prop-002', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', caption: 'Living Area', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(3) },
      { id: 'photo-006', property_id: 'demo-prop-002', url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800', caption: 'View from Deck', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(3) },
    ],
    ratings: [],
    notes: [
      { id: 'note-004', property_id: 'demo-prop-002', user_id: DEMO_BUYER_ID, content: 'Just listed - need to schedule tour ASAP!', type: 'general', created_at: daysAgo(2) },
    ],
    tags: [
      { id: 'tag-004', property_id: 'demo-prop-002', tag: 'Bay Views', created_at: daysAgo(3) },
      { id: 'tag-005', property_id: 'demo-prop-002', tag: 'In-Law Unit', created_at: daysAgo(3) },
      { id: 'tag-006', property_id: 'demo-prop-002', tag: 'Luxury', created_at: daysAgo(3) },
    ],
  },
  {
    id: 'demo-prop-003',
    household_id: DEMO_HOUSEHOLD_ID,
    address: '2847 College Avenue',
    city: 'Berkeley',
    state: 'CA',
    zip: '94705',
    county: 'Alameda',
    price: 725000,
    beds: 3,
    baths: 2,
    full_baths: 1,
    half_baths: 1,
    sqft: 1650,
    lot_size: 4500,
    year_built: 1948,
    garage: 1,
    stories: 1,
    rooms: 6,
    hoa_monthly: 0,
    property_tax_annual: 8700,
    insurance_annual: 1500,
    status: 'offer_made',
    mls_number: 'BK34567890',
    listing_date: daysAgo(28),
    property_type: 'Single Family',
    property_style: 'Mid-Century Modern',
    interior_features: ['Open Floor Plan', 'Vaulted Ceilings', 'Floor-to-Ceiling Windows', 'Original Details'],
    exterior_features: ['Large Lot', 'Mature Trees', 'Private Backyard', 'Fruit Trees'],
    appliances: ['Refrigerator', 'Gas Range', 'Dishwasher'],
    flooring: ['Original Hardwood', 'Cork'],
    heating: 'Forced Air',
    cooling: 'None',
    basement: 'Crawl Space',
    garage_type: ['Detached'],
    roof: 'Composition',
    sewer: 'Public',
    water: 'Public',
    has_in_law_suite: false,
    remarks: 'Classic mid-century modern gem in the sought-after Elmwood district. This single-story home features an open floor plan flooded with natural light. Large private backyard with mature landscaping - perfect for outdoor living. Steps from Elmwood shops, restaurants, and top-rated schools. A rare opportunity!',
    original_list_price: 749000,
    price_per_sqft: 439,
    days_on_market: 28,
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(20),
    updated_at: daysAgo(1),
    photos: [
      { id: 'photo-007', property_id: 'demo-prop-003', url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800', caption: 'Exterior', is_primary: true, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(20) },
      { id: 'photo-008', property_id: 'demo-prop-003', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', caption: 'Open Living Space', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(20) },
      { id: 'photo-009', property_id: 'demo-prop-003', url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', caption: 'Backyard', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(20) },
    ],
    ratings: [
      { id: 'rating-002', property_id: 'demo-prop-003', user_id: DEMO_BUYER_ID, rating: 5, created_at: daysAgo(15), updated_at: daysAgo(15) },
    ],
    notes: [
      { id: 'note-005', property_id: 'demo-prop-003', user_id: DEMO_BUYER_ID, content: 'Perfect single-story layout - no stairs!', type: 'pro', created_at: daysAgo(15) },
      { id: 'note-006', property_id: 'demo-prop-003', user_id: DEMO_BUYER_ID, content: 'Amazing natural light from floor-to-ceiling windows', type: 'pro', created_at: daysAgo(15) },
      { id: 'note-007', property_id: 'demo-prop-003', user_id: DEMO_BUYER_ID, content: 'Walkable to Elmwood shops and BART', type: 'pro', created_at: daysAgo(15) },
      { id: 'note-008', property_id: 'demo-prop-003', user_id: DEMO_BUYER_ID, content: 'Bathrooms need updating', type: 'con', created_at: daysAgo(15) },
      { id: 'note-009', property_id: 'demo-prop-003', user_id: DEMO_BUYER_ID, content: 'Submitted offer at $710K - waiting to hear back!', type: 'general', created_at: daysAgo(3) },
    ],
    tags: [
      { id: 'tag-007', property_id: 'demo-prop-003', tag: 'Mid-Century', created_at: daysAgo(20) },
      { id: 'tag-008', property_id: 'demo-prop-003', tag: 'Single Story', created_at: daysAgo(20) },
      { id: 'tag-009', property_id: 'demo-prop-003', tag: 'Good Schools', created_at: daysAgo(20) },
      { id: 'tag-010', property_id: 'demo-prop-003', tag: 'Favorite', created_at: daysAgo(15) },
    ],
  },
  {
    id: 'demo-prop-004',
    household_id: DEMO_HOUSEHOLD_ID,
    address: '456 Grand Lake Drive',
    city: 'Oakland',
    state: 'CA',
    zip: '94610',
    county: 'Alameda',
    price: 685000,
    beds: 2,
    baths: 2,
    full_baths: 2,
    half_baths: 0,
    sqft: 1400,
    lot_size: 0,
    year_built: 2018,
    garage: 1,
    stories: 1,
    rooms: 5,
    hoa_monthly: 450,
    property_tax_annual: 8200,
    insurance_annual: 1200,
    status: 'interested',
    mls_number: 'OK45678901',
    listing_date: daysAgo(7),
    property_type: 'Condo',
    property_style: 'Contemporary',
    interior_features: ['Modern Finishes', 'In-Unit Laundry', 'Walk-in Closet', 'Balcony', 'Smart Thermostat'],
    exterior_features: ['Shared Rooftop Deck', 'Community Garden', 'Bike Storage'],
    appliances: ['Stainless Refrigerator', 'Gas Range', 'Dishwasher', 'Washer/Dryer'],
    flooring: ['Engineered Hardwood', 'Tile'],
    heating: 'Forced Air',
    cooling: 'Central AC',
    basement: 'None',
    garage_type: ['Underground'],
    roof: 'Flat',
    sewer: 'Public',
    water: 'Public',
    has_in_law_suite: false,
    remarks: 'Modern luxury living in the heart of Grand Lake! This like-new 2BR/2BA condo features high-end finishes throughout. Open concept living with chef\'s kitchen, quartz counters, and premium appliances. Walking distance to Lake Merritt, Whole Foods, and excellent dining options. HOA includes water, trash, and common area maintenance.',
    original_list_price: 699000,
    price_per_sqft: 489,
    days_on_market: 7,
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    photos: [
      { id: 'photo-010', property_id: 'demo-prop-004', url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800', caption: 'Building Exterior', is_primary: true, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(5) },
      { id: 'photo-011', property_id: 'demo-prop-004', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', caption: 'Open Living Area', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(5) },
    ],
    ratings: [
      { id: 'rating-003', property_id: 'demo-prop-004', user_id: DEMO_BUYER_ID, rating: 3, created_at: daysAgo(4), updated_at: daysAgo(4) },
    ],
    notes: [
      { id: 'note-010', property_id: 'demo-prop-004', user_id: DEMO_BUYER_ID, content: 'Modern finishes and move-in ready', type: 'pro', created_at: daysAgo(4) },
      { id: 'note-011', property_id: 'demo-prop-004', user_id: DEMO_BUYER_ID, content: 'Great location near Lake Merritt', type: 'pro', created_at: daysAgo(4) },
      { id: 'note-012', property_id: 'demo-prop-004', user_id: DEMO_BUYER_ID, content: 'HOA is $450/month - quite high', type: 'con', created_at: daysAgo(4) },
      { id: 'note-013', property_id: 'demo-prop-004', user_id: DEMO_BUYER_ID, content: 'Only 2 bedrooms - might be tight', type: 'con', created_at: daysAgo(4) },
    ],
    tags: [
      { id: 'tag-011', property_id: 'demo-prop-004', tag: 'Condo', created_at: daysAgo(5) },
      { id: 'tag-012', property_id: 'demo-prop-004', tag: 'New Construction', created_at: daysAgo(5) },
      { id: 'tag-013', property_id: 'demo-prop-004', tag: 'Lake Views', created_at: daysAgo(5) },
    ],
  },
  {
    id: 'demo-prop-005',
    household_id: DEMO_HOUSEHOLD_ID,
    address: '3921 Summit Road',
    city: 'Oakland',
    state: 'CA',
    zip: '94611',
    county: 'Alameda',
    price: 1150000,
    beds: 5,
    baths: 3.5,
    full_baths: 3,
    half_baths: 1,
    sqft: 3200,
    lot_size: 8500,
    year_built: 1965,
    year_renovated: 2020,
    garage: 2,
    stories: 2,
    rooms: 11,
    hoa_monthly: 0,
    property_tax_annual: 13800,
    insurance_annual: 2200,
    status: 'toured',
    mls_number: 'OK56789012',
    listing_date: daysAgo(45),
    property_type: 'Single Family',
    property_style: 'Contemporary',
    interior_features: ['Panoramic Views', 'Great Room', 'Home Theater', 'Wet Bar', 'Multiple Decks'],
    exterior_features: ['Pool', 'Outdoor Kitchen', 'View Lot', 'Drought-Tolerant Landscaping'],
    appliances: ['Built-in Refrigerator', 'Double Oven', 'Wine Refrigerator', 'Central Vacuum'],
    flooring: ['Hardwood', 'Porcelain Tile', 'Carpet'],
    heating: 'Forced Air',
    cooling: 'Central AC',
    basement: 'None',
    garage_type: ['Attached'],
    roof: 'Tile',
    sewer: 'Public',
    water: 'Public',
    has_in_law_suite: true,
    in_law_features: ['Separate Entrance', 'Full Kitchen', 'Full Bath', 'Bedroom'],
    remarks: 'Spectacular Oakland Hills estate with jaw-dropping Bay views! This extensively remodeled home offers 5 bedrooms including a separate in-law suite. Resort-style backyard features a pool, spa, and outdoor kitchen. Main level great room with walls of glass framing the panoramic views. Perfect for entertaining or multi-generational living.',
    original_list_price: 1295000,
    price_per_sqft: 359,
    days_on_market: 45,
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(30),
    updated_at: daysAgo(5),
    photos: [
      { id: 'photo-012', property_id: 'demo-prop-005', url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800', caption: 'Exterior with Pool', is_primary: true, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(30) },
      { id: 'photo-013', property_id: 'demo-prop-005', url: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800', caption: 'Great Room', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(30) },
      { id: 'photo-014', property_id: 'demo-prop-005', url: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800', caption: 'View from Deck', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(30) },
      { id: 'photo-015', property_id: 'demo-prop-005', url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800', caption: 'Pool Area', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(30) },
    ],
    ratings: [
      { id: 'rating-004', property_id: 'demo-prop-005', user_id: DEMO_BUYER_ID, rating: 4, created_at: daysAgo(20), updated_at: daysAgo(20) },
    ],
    notes: [
      { id: 'note-014', property_id: 'demo-prop-005', user_id: DEMO_BUYER_ID, content: 'Incredible views from every room!', type: 'pro', created_at: daysAgo(20) },
      { id: 'note-015', property_id: 'demo-prop-005', user_id: DEMO_BUYER_ID, content: 'Pool and outdoor kitchen are amazing for entertaining', type: 'pro', created_at: daysAgo(20) },
      { id: 'note-016', property_id: 'demo-prop-005', user_id: DEMO_BUYER_ID, content: 'In-law suite perfect for parents to visit', type: 'pro', created_at: daysAgo(20) },
      { id: 'note-017', property_id: 'demo-prop-005', user_id: DEMO_BUYER_ID, content: 'Price reduced $145K - motivated seller?', type: 'general', created_at: daysAgo(10) },
      { id: 'note-018', property_id: 'demo-prop-005', user_id: DEMO_BUYER_ID, content: 'Fire insurance might be expensive in hills', type: 'con', created_at: daysAgo(20) },
      { id: 'note-019', property_id: 'demo-prop-005', user_id: DEMO_BUYER_ID, content: 'Winding road access - could be tough in bad weather', type: 'con', created_at: daysAgo(20) },
    ],
    tags: [
      { id: 'tag-014', property_id: 'demo-prop-005', tag: 'Pool', created_at: daysAgo(30) },
      { id: 'tag-015', property_id: 'demo-prop-005', tag: 'Views', created_at: daysAgo(30) },
      { id: 'tag-016', property_id: 'demo-prop-005', tag: 'In-Law Unit', created_at: daysAgo(30) },
      { id: 'tag-017', property_id: 'demo-prop-005', tag: 'Price Reduced', created_at: daysAgo(10) },
    ],
  },
  {
    id: 'demo-prop-006',
    household_id: DEMO_HOUSEHOLD_ID,
    address: '892 Marina Boulevard',
    city: 'San Francisco',
    state: 'CA',
    zip: '94123',
    county: 'San Francisco',
    price: 2450000,
    beds: 4,
    baths: 3.5,
    full_baths: 3,
    half_baths: 1,
    sqft: 2800,
    lot_size: 2800,
    year_built: 1920,
    year_renovated: 2022,
    garage: 2,
    stories: 3,
    rooms: 10,
    hoa_monthly: 0,
    property_tax_annual: 29400,
    insurance_annual: 4800,
    status: 'rejected',
    mls_number: 'SF67890123',
    listing_date: daysAgo(60),
    property_type: 'Single Family',
    property_style: 'Mediterranean',
    interior_features: ['Designer Kitchen', 'Primary Suite with View', 'Elevator', 'Wine Room', 'Au Pair Suite'],
    exterior_features: ['Golden Gate Views', 'Private Patio', 'Rooftop Terrace', 'Outdoor Fireplace'],
    appliances: ['Miele Appliances', 'Sub-Zero', 'Built-in Coffee System'],
    flooring: ['White Oak', 'Italian Marble', 'Heated Floors'],
    heating: 'Radiant',
    cooling: 'Central AC',
    basement: 'Full - Finished',
    garage_type: ['Built-in', 'Electric Vehicle Ready'],
    roof: 'Tile',
    sewer: 'Public',
    water: 'Public',
    has_in_law_suite: true,
    remarks: 'Iconic Marina gem with Golden Gate Bridge views from every level! This meticulously renovated Mediterranean estate offers the finest in San Francisco living. Custom finishes throughout, including a chef\'s kitchen, spa-like bathrooms, and a climate-controlled wine room. Private elevator serves all floors. Au pair suite with separate entrance.',
    original_list_price: 2695000,
    price_per_sqft: 875,
    days_on_market: 60,
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(45),
    updated_at: daysAgo(30),
    photos: [
      { id: 'photo-016', property_id: 'demo-prop-006', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800', caption: 'Mediterranean Exterior', is_primary: true, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(45) },
      { id: 'photo-017', property_id: 'demo-prop-006', url: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800', caption: 'Gourmet Kitchen', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(45) },
      { id: 'photo-018', property_id: 'demo-prop-006', url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800', caption: 'Primary Suite', is_primary: false, uploaded_by: DEMO_BUYER_ID, created_at: daysAgo(45) },
    ],
    ratings: [
      { id: 'rating-005', property_id: 'demo-prop-006', user_id: DEMO_BUYER_ID, rating: 2, created_at: daysAgo(40), updated_at: daysAgo(40) },
    ],
    notes: [
      { id: 'note-020', property_id: 'demo-prop-006', user_id: DEMO_BUYER_ID, content: 'Stunning property but way over budget', type: 'con', created_at: daysAgo(40) },
      { id: 'note-021', property_id: 'demo-prop-006', user_id: DEMO_BUYER_ID, content: 'Golden Gate views are incredible', type: 'pro', created_at: daysAgo(40) },
      { id: 'note-022', property_id: 'demo-prop-006', user_id: DEMO_BUYER_ID, content: 'Wine room and elevator are nice-to-haves we don\'t need', type: 'general', created_at: daysAgo(40) },
      { id: 'note-023', property_id: 'demo-prop-006', user_id: DEMO_BUYER_ID, content: 'Decided to pass - doesn\'t fit our budget or needs', type: 'general', created_at: daysAgo(30) },
    ],
    tags: [
      { id: 'tag-018', property_id: 'demo-prop-006', tag: 'Luxury', created_at: daysAgo(45) },
      { id: 'tag-019', property_id: 'demo-prop-006', tag: 'Bridge Views', created_at: daysAgo(45) },
      { id: 'tag-020', property_id: 'demo-prop-006', tag: 'Over Budget', created_at: daysAgo(40) },
    ],
  },
];

// Demo Clients (for Broker view)
export const demoClients: Client[] = [
  {
    id: 'demo-client-001',
    name: 'Michael & Lisa Chen',
    email: 'chen.family@email.com',
    phone: '(415) 555-1234',
    status: 'active',
    source: 'Referral',
    budget_min: 800000,
    budget_max: 1100000,
    preferred_beds: 4,
    preferred_baths: 2.5,
    preferred_locations: ['San Francisco', 'Daly City', 'South San Francisco'],
    timeline: 'asap',
    pre_approved: true,
    pre_approval_amount: 1050000,
    notes: 'Looking for good schools, family-friendly neighborhood. Flexible on property style. Both work downtown, prefer short commute. Very motivated - lease ends in 60 days!',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(45),
    updated_at: daysAgo(2),
    linked_properties: [
      { id: 'lp-001', client_id: 'demo-client-001', property_id: 'demo-prop-001', status: 'shown', shown_date: daysAgo(5), feedback: 'Loved the kitchen, concerned about street noise', rating: 4, created_at: daysAgo(5), updated_at: daysAgo(5) },
      { id: 'lp-002', client_id: 'demo-client-001', property_id: 'demo-prop-002', status: 'interested', created_at: daysAgo(2), updated_at: daysAgo(2) },
      { id: 'lp-007', client_id: 'demo-client-001', property_id: 'demo-prop-003', status: 'offer_made', shown_date: daysAgo(10), feedback: 'This is the one! Making an offer.', rating: 5, created_at: daysAgo(12), updated_at: daysAgo(3) },
    ],
  },
  {
    id: 'demo-client-002',
    name: 'David Rodriguez',
    email: 'david.r@techco.com',
    phone: '(510) 555-5678',
    status: 'active',
    source: 'Website',
    budget_min: 600000,
    budget_max: 800000,
    preferred_beds: 2,
    preferred_baths: 2,
    preferred_locations: ['Oakland', 'Berkeley', 'Emeryville'],
    timeline: 'asap',
    pre_approved: true,
    pre_approval_amount: 780000,
    notes: 'First-time buyer, works from home, needs dedicated office space. Interested in newer construction or recently renovated.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(20),
    updated_at: daysAgo(1),
    linked_properties: [
      { id: 'lp-003', client_id: 'demo-client-002', property_id: 'demo-prop-003', status: 'offer_made', shown_date: daysAgo(10), feedback: 'Perfect location, making an offer!', rating: 5, created_at: daysAgo(15), updated_at: daysAgo(3) },
      { id: 'lp-004', client_id: 'demo-client-002', property_id: 'demo-prop-004', status: 'shown', shown_date: daysAgo(8), feedback: 'Nice but HOA too high', rating: 3, created_at: daysAgo(12), updated_at: daysAgo(8) },
    ],
  },
  {
    id: 'demo-client-003',
    name: 'Jennifer & Mark Thompson',
    email: 'thompson.family@email.com',
    phone: '(650) 555-9012',
    status: 'active',
    source: 'Open House',
    budget_min: 1200000,
    budget_max: 1800000,
    preferred_beds: 5,
    preferred_baths: 3,
    preferred_locations: ['Piedmont', 'Oakland Hills', 'Lafayette'],
    timeline: '3-6_months',
    pre_approved: true,
    pre_approval_amount: 1750000,
    notes: 'Relocating from Chicago. Need space for 3 kids and home office. Strong school district is priority. Looking at both single family and larger townhomes.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(30),
    updated_at: daysAgo(7),
    linked_properties: [
      { id: 'lp-005', client_id: 'demo-client-003', property_id: 'demo-prop-005', status: 'shown', shown_date: daysAgo(14), feedback: 'Love the views and pool, kids loved it!', rating: 5, created_at: daysAgo(20), updated_at: daysAgo(14) },
    ],
  },
  {
    id: 'demo-client-004',
    name: 'Emma Wilson',
    email: 'emma.wilson@startup.io',
    phone: '(415) 555-3456',
    status: 'active',
    source: 'Zillow',
    budget_min: 500000,
    budget_max: 700000,
    preferred_beds: 1,
    preferred_baths: 1,
    preferred_locations: ['San Francisco', 'Oakland'],
    timeline: '6-12_months',
    pre_approved: false,
    notes: 'Young professional, looking for investment property. Interested in condos near transit. Working on getting pre-approved.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(60),
    updated_at: daysAgo(14),
    linked_properties: [],
  },
  {
    id: 'demo-client-005',
    name: 'Robert & Maria Santos',
    email: 'santos.family@email.com',
    phone: '(925) 555-7890',
    status: 'inactive',
    source: 'Referral',
    budget_min: 900000,
    budget_max: 1200000,
    preferred_beds: 4,
    preferred_baths: 3,
    preferred_locations: ['Walnut Creek', 'Danville', 'San Ramon'],
    timeline: '6-12_months',
    pre_approved: true,
    pre_approval_amount: 1100000,
    notes: 'Put search on hold due to job change. Will resume in 3-4 months. Keep in touch with market updates.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(90),
    updated_at: daysAgo(30),
    linked_properties: [],
  },
  {
    id: 'demo-client-006',
    name: 'James Park',
    email: 'james.park@consulting.com',
    phone: '(408) 555-2345',
    status: 'closed',
    source: 'Past Client Referral',
    budget_min: 1500000,
    budget_max: 2000000,
    preferred_beds: 3,
    preferred_baths: 2.5,
    preferred_locations: ['Palo Alto', 'Menlo Park', 'Los Altos'],
    timeline: 'asap',
    pre_approved: true,
    pre_approval_amount: 1900000,
    notes: 'Successfully closed on a property in Los Altos! Great client, promised to refer colleagues.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(120),
    updated_at: daysAgo(15),
    linked_properties: [
      { id: 'lp-006', client_id: 'demo-client-006', property_id: 'demo-prop-006', status: 'closed', shown_date: daysAgo(45), feedback: 'Closed!', rating: 5, created_at: daysAgo(90), updated_at: daysAgo(15) },
    ],
  },
  {
    id: 'demo-client-007',
    name: 'Priya & Raj Patel',
    email: 'patel.family@gmail.com',
    phone: '(510) 555-8888',
    status: 'active',
    source: 'Open House',
    budget_min: 950000,
    budget_max: 1300000,
    preferred_beds: 4,
    preferred_baths: 3,
    preferred_locations: ['Fremont', 'Newark', 'Union City'],
    timeline: '1-3_months',
    pre_approved: true,
    pre_approval_amount: 1250000,
    notes: 'Tech couple relocating from Seattle. Need good schools for 2 kids (ages 5 and 8). Want modern home with open floor plan. Prefer newer construction. Very organized buyers.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(14),
    updated_at: daysAgo(1),
    linked_properties: [
      { id: 'lp-008', client_id: 'demo-client-007', property_id: 'demo-prop-004', status: 'shown', shown_date: daysAgo(7), feedback: 'Too small for our family', rating: 2, created_at: daysAgo(10), updated_at: daysAgo(7) },
      { id: 'lp-009', client_id: 'demo-client-007', property_id: 'demo-prop-005', status: 'interested', created_at: daysAgo(3), updated_at: daysAgo(3) },
    ],
  },
  {
    id: 'demo-client-008',
    name: 'Amanda Foster',
    email: 'amanda.foster@lawfirm.com',
    phone: '(415) 555-9999',
    status: 'active',
    source: 'Instagram Ad',
    budget_min: 700000,
    budget_max: 900000,
    preferred_beds: 2,
    preferred_baths: 2,
    preferred_locations: ['San Francisco', 'Oakland'],
    timeline: '3-6_months',
    pre_approved: true,
    pre_approval_amount: 850000,
    notes: 'Single professional, attorney at downtown firm. Wants urban lifestyle - walkable neighborhood, close to restaurants/nightlife. Prefers condo or townhouse. No yard maintenance.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(21),
    updated_at: daysAgo(5),
    linked_properties: [
      { id: 'lp-010', client_id: 'demo-client-008', property_id: 'demo-prop-004', status: 'interested', created_at: daysAgo(5), updated_at: daysAgo(5) },
    ],
  },
  {
    id: 'demo-client-009',
    name: 'Carlos & Maria Gonzalez',
    email: 'gonzalez.carlos@email.com',
    phone: '(650) 555-3333',
    status: 'active',
    source: 'Zillow',
    budget_min: 600000,
    budget_max: 750000,
    preferred_beds: 3,
    preferred_baths: 2,
    preferred_locations: ['Redwood City', 'San Mateo', 'East Palo Alto'],
    timeline: 'asap',
    pre_approved: false,
    notes: 'First-time buyers, currently renting. Working on getting pre-approved - referred them to my mortgage contact. Budget is tight but very motivated. Need to move before school year starts.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
    linked_properties: [],
  },
  {
    id: 'demo-client-010',
    name: 'William & Dorothy Chang',
    email: 'chang.william@retired.com',
    phone: '(925) 555-7777',
    status: 'active',
    source: 'Referral',
    budget_min: 800000,
    budget_max: 1000000,
    preferred_beds: 2,
    preferred_baths: 2,
    preferred_locations: ['Walnut Creek', 'Pleasant Hill', 'Lafayette'],
    timeline: '6-12_months',
    pre_approved: true,
    pre_approval_amount: 950000,
    notes: 'Empty nesters downsizing from 4BR home in Orinda. Want single-story, low maintenance. No rush - current home not yet listed. Interested in 55+ communities or quiet neighborhoods.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(60),
    updated_at: daysAgo(14),
    linked_properties: [],
  },
  {
    id: 'demo-client-011',
    name: 'Kevin O\'Brien',
    email: 'kevin.obrien@investor.com',
    phone: '(408) 555-4444',
    status: 'active',
    source: 'LinkedIn',
    budget_min: 500000,
    budget_max: 800000,
    preferred_beds: 2,
    preferred_baths: 1,
    preferred_locations: ['San Jose', 'Santa Clara', 'Milpitas'],
    timeline: '1-3_months',
    pre_approved: true,
    pre_approval_amount: 750000,
    notes: 'Investor looking for rental property. Wants positive cash flow from day one. Prefers multi-family or condo with low HOA. Has purchased 3 properties with me before - very decisive.',
    created_by: DEMO_BROKER_ID,
    household_id: DEMO_HOUSEHOLD_ID,
    created_at: daysAgo(10),
    updated_at: daysAgo(2),
    linked_properties: [
      { id: 'lp-011', client_id: 'demo-client-011', property_id: 'demo-prop-004', status: 'shown', shown_date: daysAgo(4), feedback: 'HOA too high for rental returns', rating: 3, created_at: daysAgo(6), updated_at: daysAgo(4) },
    ],
  },
];

// Demo Showings (for Broker view)
export const demoShowings: Showing[] = [
  {
    id: 'demo-showing-001',
    property_id: 'demo-prop-001',
    client_id: 'demo-client-001',
    scheduled_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // Tomorrow
    scheduled_time: '14:00',
    duration_minutes: 45,
    status: 'scheduled',
    notes: 'Couple very interested. Bring comps for the area.',
    created_by: DEMO_BROKER_ID,
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-showing-002',
    property_id: 'demo-prop-002',
    client_id: 'demo-client-001',
    scheduled_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // Day after tomorrow
    scheduled_time: '10:30',
    duration_minutes: 60,
    status: 'scheduled',
    notes: 'Pacific Heights showing. Meet at property.',
    created_by: DEMO_BROKER_ID,
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-showing-003',
    property_id: 'demo-prop-004',
    client_id: 'demo-client-002',
    scheduled_date: daysAgo(8).split('T')[0],
    scheduled_time: '16:00',
    duration_minutes: 30,
    status: 'completed',
    notes: 'Initial showing of Grand Lake condo',
    feedback: 'David liked the modern finishes but thought HOA was too high. Will keep looking.',
    rating: 3,
    created_by: DEMO_BROKER_ID,
    created_at: daysAgo(12),
    updated_at: daysAgo(8),
  },
  {
    id: 'demo-showing-004',
    property_id: 'demo-prop-005',
    client_id: 'demo-client-003',
    scheduled_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    scheduled_time: '11:00',
    duration_minutes: 60,
    status: 'scheduled',
    notes: 'Second showing - bringing extended family to see the property',
    created_by: DEMO_BROKER_ID,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
];

// Demo Activities
export const demoActivities = [
  {
    id: 'activity-001',
    property_id: 'demo-prop-003',
    type: 'offer_made' as const,
    description: 'Offer submitted for $710,000 on 2847 College Avenue',
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(3),
  },
  {
    id: 'activity-002',
    property_id: 'demo-prop-001',
    type: 'showing_completed' as const,
    description: 'Completed tour of 742 Maple Street',
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(5),
  },
  {
    id: 'activity-003',
    property_id: 'demo-prop-005',
    type: 'price_change' as const,
    description: 'Price reduced from $1,295,000 to $1,150,000',
    metadata: { old_price: 1295000, new_price: 1150000 },
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(10),
  },
  {
    id: 'activity-004',
    property_id: 'demo-prop-002',
    type: 'property_added' as const,
    description: 'Added 1580 Pacific Heights Blvd to watchlist',
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(3),
  },
];

// Demo Offers
export const demoOffers = [
  {
    id: 'offer-001',
    property_id: 'demo-prop-003',
    amount: 710000,
    offer_date: daysAgo(3),
    expiration_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'submitted' as const,
    contingencies: ['Inspection', 'Financing', 'Appraisal'],
    earnest_money: 21000,
    closing_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    notes: 'Offering below asking due to time on market. Open to negotiation.',
    created_by: DEMO_BUYER_ID,
    created_at: daysAgo(3),
    updated_at: daysAgo(2),
  },
];

/**
 * Check if user is in demo mode
 */
export function isDemoMode(userId: string | undefined): boolean {
  return userId === DEMO_BUYER_ID || userId === DEMO_BROKER_ID;
}

/**
 * Get demo user based on type
 */
export function getDemoUser(type: 'buyer' | 'broker'): User {
  return type === 'buyer' ? demoBuyerUser : demoBrokerUser;
}
